{{- if and .Values.backup.enabled (not .Values.garage.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-backup
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  S3_ACCESS_KEY: {{ .Values.backup.s3.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.backup.s3.secretKey | quote }}
{{- end }}
