{{- if .Values.garage.enabled }}
{{- $fullname := include "clickhouse.fullname" . }}
{{- $secretName := printf "%s-garage-secret" $fullname }}
{{- $prevSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
{{- $prevData := $prevSecret.data | default dict }}
{{- $prevRpcSecret := $prevData.rpcSecret | default "" | b64dec }}
{{- $prevAdminToken := $prevData.adminToken | default "" | b64dec }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: garage
type: Opaque
data:
  rpcSecret: {{ .Values.garage.rpcSecret | default $prevRpcSecret | default (include "clickhouse.randHex" 64) | b64enc | quote }}
  adminToken: {{ .Values.garage.adminToken | default $prevAdminToken | default (include "clickhouse.randHex" 32) | b64enc | quote }}
{{- end }}
